name: mi_aplicacion_flutter
description: "Una nueva aplicación Flutter para gestionar gastos."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Agrega tus assets aquí
  assets:
    - assets/images/

  # Agrega tus fuentes personalizadas aquí si tienes alguna
  # fonts:
  #   - family: TuFuentePersonalizada
  #     fonts:
  #       - asset: fonts/TuFuentePersonalizada-Regular.ttf
  #       - asset: fonts/TuFuentePersonalizada-Italic.ttf
  #         style: italic
